# Generated by Django 4.0.3 on 2022-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
